tudat-team/tudatpy

- tudatpy/kernel/expose_numerical_simulation/expose_environment.cpp
See https://github.com/tudat-team/tudat/issues/21
> Added possibility to reset tabulated ephemeris with Xd vectors

- tests/test_dse_functions.py
- tudatpy/util/__init__.py
- tudatpy/util/_dse_functions.py
This pull request includes three functions — added to the util module of tudatpy — related to a Design Space Exploration (DSE): get_orthogonal_array(), get_yates_array(), and anova_analysis(). These functions can be used to conduct a more thorough exploration, as a systematic alternative to the more brainless Monte Carlo analysis. In addition, I have implemented a few unit tests for the first two functions, which are referenced in the source file. The third function has not independently been verified yet, only a circular 'self-verification' is implemented.
> Adding DSE functions to util.

- tudatpy/kernel/expose_numerical_simulation/expose_propagation_setup/expose_propagator_setup.cpp
This PR is limited to the exposure of the "non-sequential termination settings", but goes in pair with the new non-sequential propagation/estimation features.
> exposed non-sequential termination settings.

- tudatpy/data/mpc.py
- tudatpy/data/sbdb.py
This PR changes a few lines added while completing [The MPC examples](https://github.com/tudat-team/tudatpy-examples/pull/28).
These changes were made after merging https://github.com/tudat-team/tudatpy/pull/110.
PR is required to run estimation example,
> MPC + SBDB quick fix to run examples

- tudatpy/kernel/expose_astro/expose_element_conversion.cpp
- tudatpy/kernel/expose_numerical_simulation/expose_environment.cpp
- tudatpy/kernel/expose_numerical_simulation/expose_environment_setup.cpp
- tudatpy/kernel/expose_numerical_simulation/expose_estimation_setup/expose_observation_setup.cpp
exposed functions to use atmospheric models and ancillary settings
> added a couple functions for develop

- tudatpy/kernel/expose_numerical_simulation/expose_propagation_setup/expose_acceleration_setup.cpp
This request is linked to https://github.com/tudat-team/tudat-multidoc/pull/80
> Add acceleration enumerations

- tudatpy/data/__init__.py
- tudatpy/kernel/expose_io.cpp
- tudatpy/kernel/expose_numerical_simulation/expose_estimation_setup/expose_observation_setup.cpp
- tudatpy/numerical_simulation/estimation_setup/observation/_import_all_kernel_members.py
This pull request exposes the necessary functionality to allow reading observations from a text file and setting up the [MRO range example](https://github.com/tudat-team/tudatpy-examples/pull/42).
> Exposing functionality for reading txt tracking files

- tests/test_data_mpc.py
This PR removes one of the tests introduced in https://github.com/tudat-team/tudatpy/pull/137 which was causing issues in the build.
> Remove test_BatchMPC_filter to fix mpc tests

- docs/source/ephemeris.rst
- docs/source/gravity_field.rst
- docs/source/propagation.rst
- tudatpy/numerical_simulation/propagation/dependent_variable_dictionary/dependent_variable_dictionary.py
> Render python native docs on API docs website

- tudatpy/CMakeLists.txt
- tudatpy/kernel/expose_astro.cpp
- tudatpy/kernel/expose_astro/expose_timing_system.cpp
- tudatpy/kernel/expose_astro/expose_timing_system.h
- tudatpy/kernel/expose_math.cpp
- tudatpy/kernel/expose_math/expose_statistics.cpp
- tudatpy/kernel/expose_math/expose_statistics.h
- tudatpy/kernel/expose_numerical_simulation.cpp
- tudatpy/kernel/expose_numerical_simulation/expose_environment.cpp
- tudatpy/kernel/expose_numerical_simulation/expose_estimation_setup/expose_estimated_parameter_setup.cpp
- tudatpy/kernel/expose_numerical_simulation/expose_estimation_setup/expose_observation_setup.cpp
exposed clock noise functions for tudatpy
> exposed clock noise functions

- tudatpy/kernel/expose_numerical_simulation/expose_environment_setup/expose_gravity_field_setup.cpp
Fix wrong mapping of goco05c spherical harmonics model
> Fix goco05c enum exposure

- docs/source/astro.rst
- docs/source/fundamentals.rst
- tudatpy/kernel/docstrings.h
- tudatpy/kernel/expose_astro/expose_fundamentals.cpp
Add `compute_shadow_function` to the API docs, after being requested by @snoopy-tue in https://github.com/orgs/tudat-team/discussions/4.
> Document compute_shadow_function

- docs/source/environment_setup.rst
- tudatpy/kernel/expose_data.cpp
- tudatpy/kernel/expose_math/expose_interpolators.cpp
- tudatpy/kernel/expose_numerical_simulation/expose_environment_setup.cpp
- Add BodyListSettings docs, some more BodySettings attributes
- Add data docstrings from io module
- Reorder interpolator exposure so return types can be inferred by pybind
> Docstring updates

- docs/source/numerical_simulation.rst
- tudatpy/kernel/expose_numerical_simulation/expose_estimation_propagated_covariance.cpp
- tudatpy/kernel/expose_numerical_simulation/expose_propagation.cpp
- tudatpy/kernel/expose_numerical_simulation/expose_propagation_setup/expose_propagator_setup.cpp
- tudatpy/kernel/expose_numerical_simulation_simulator.cpp
- tudatpy/kernel/expose_numerical_simulation_variational.cpp
Minor corrections for second NA assignment:
- Add `create_variational_equations_solver` back to API reference
- Move function definitions to end of exposures, add DynamicsSimulator base class, so types can be inferred
- Add example how hybrid termination conditions can be read-out (fixes #233)
> NA Assignment 2 API additions

- tudatpy/kernel/expose_numerical_simulation/expose_estimation_setup/expose_estimated_parameter_setup.cpp
Added `periodic_gravity_field_variation_amplitudes` as requested by Riwa.
> Added periodic_gravity_field_variation_amplitudes exposure

- docs/source/observation.rst
- tudatpy/kernel/expose_numerical_simulation/expose_estimation_setup/expose_observation_setup.cpp
- Update model description for relative angular observable
- Expose LinkEnd enums for relative position observable
- Add relative position observable to API
> Update docs for relative position and angular observables

- docs/source/parameter.rst
- src/tudatpy/numerical_simulation/estimation_setup/parameter/expose_parameter.cpp
Add empirical acceleleration enums to API reference, add docs to enum exposures.
> add docs for empirical acceleration enums

- src/tudatpy/data/mission_data_downloader.py
- Modified kernel loading behaviour to avoid redundant loading when a meta-kernel file is present.
- If 'mk' (meta-kernel) is included in the kernel_files_to_load and load_kernels is True:
→ Only the meta-kernel is
→ All referenced kernel files, including the meta-kernel, are added to self.all_kernel_files.
- If no meta-kernel is present:
→ Each kernel is loaded individually if load_kernels is True.
→ All converted kernels are added to self.all_kernel_files as before.
- Ensures clean separation of loading logic and kernel tracking without duplication.
> fixed kernel loading logic based on presence of meta-kernel

- docs/source/environment.rst
- docs/source/gravity_field_variation.rst
- docs/source/propagation.rst
- src/tudatpy/numerical_simulation/environment/expose_environment.cpp
- src/tudatpy/numerical_simulation/environment_setup/aerodynamic_coefficients/expose_aerodynamic_coefficients.cpp
- src/tudatpy/numerical_simulation/environment_setup/gravity_field_variation/expose_gravity_field_variation.cpp
- src/tudatpy/numerical_simulation/propagation/expose_propagation.cpp
Addressing a subset of issues listed here:
https://github.com/tudat-team/tudatpy/issues/211
> Adding docstrings

- docs/tudatpy/source/estimation/observable_models_setup/model_settings.rst
- src/tudatpy/data/mission_data_downloader.py
- src/tudatpy/data/processTrk234/converters/derivedDoppler.py
- src/tudatpy/dynamics/environment_setup/rotation_model/expose_rotation_model.cpp
- src/tudatpy/dynamics/parameters_setup/expose_parameters_setup.cpp
- src/tudatpy/dynamics/propagation/expose_propagation.cpp
- src/tudatpy/dynamics/propagation_setup/propagator/expose_propagator.cpp
- src/tudatpy/estimation/observable_models_setup/light_time_corrections/expose_light_time_corrections.cpp
- src/tudatpy/estimation/observable_models_setup/model_settings/expose_model_settings.cpp
- src/tudatpy/util/_support.py
A few minor updates I encountered while working on #365. Together with #365, this should result in an error-free API docs build.
> Minor error resolution updates for API docs

- src/tudatpy/numerical_simulation/environment/expose_environment.cpp
Exposed set_transmitted_frequency_calculator
> Exposed vehicle systems set_transmitted_frequency_calculator

- src/tudatpy/data/expose_data.cpp
This PR exposes the `set_estrack_weather_in_ground_stations` function.
> Added exposure

- src/tudatpy/dynamics/parameters_setup/expose_parameters_setup.cpp
> expose parameters associated with rtg force model
