tudatpy/kernel/expose_numerical_simulation.cpp, tudatpy/util/__init__.py, tudatpy/util/_support.py
This branch implements the two utilities that @Marchesini010126 suggested in [this issue](https://github.com/tudat-team/tudat-space/issues/65).
I exposed `getIntegratedTypeAndBodyList` from `tudat::propagators` as `tudatpy.kernel.numerical_simulation.get_integrated_type_and_body_list` to make the `split_history` function work (as we need to know what bodies are propagated, and most importantly what type of states). I didn't make docstrings for it, as I don't think it should be too visible to tudatpy users.
The docstrings of the two new functions can be found directly in the function definitions. I will push directly to `tudat-multidoc` to make them active in the API docs when this pull request is approved.
=> New split_history and vector2matrix utils

tudatpy/kernel/expose_numerical_simulation/expose_propagation_setup/expose_propagator_setup.cpp
Exposed the `CustomStatePropagatorSettings` class in the same way the other propagator settings are exposed.
=> exposed CustomStatePropagator settings

tudatpy/kernel/expose_numerical_simulation/expose_estimation.cpp
Added the python exposure of the function "setConstantPerObservableAndLinkEndsWeights". This allows for adding constant 
weights to observations depending on the observable type and link-ends for the covariance analysis.
Python example:
```
noise_level = 1e-3
range_type = observation.one_way_range_type
link_ends_dict = { observation.transmitter: observation.body_origin_link_end_id(<transmitter_name>),                        
observation.receiver: observation.body_origin_link_end_id(<receiver_name>)
}
pod_input = estimation.CovarianceAnalysisInput(<simulated_observations>)
pod_input.set_constant_weight_per_observable_and_link_end(range_type, link_ends_dict, noise_level)
```
**Note**: the python syntax for this function is different from other functions used to define the weight matrix. The …
=> Exposed the function "setConstantPerObservableAndLinkEndsWeights" to Python

tudatpy/kernel/expose_numerical_simulation/expose_propagation.cpp, tudatpy/kernel/expose_numerical_simulation/expose_propagation_setup/expose_dependent_variable_setup.cpp, tudatpy/kernel/expose_numerical_simulation/expose_propagation_setup/expose_propagator_setup.cpp
Functionality to address: https://github.com/tudat-team/tudat/issues/179
Main new functionality:
* The original list of dependent variable settings can now be retrieved from the SingleArcSimulationResults
* A dictionary with the (start index, size) as value and the associated dependent variable save settings as value can now be accessed from the SingleArcSimulationResults
* Free functions to get the size (int) and shape (int: rows, int: cols) are now exposed
The associated tudat pull request is here:
https://github.com/tudat-team/tudat/pull/181
=> Improved dependent variable access

tests/test_hybrid_module_exposure.py, tudatpy/__init__.py, tudatpy/kernel_hybrid/trajectory_design/porkchop/_lambert.py, tudatpy/kernel_hybrid/trajectory_design/porkchop/porkchop.py, tudatpy/setup_hybrid_modules.py
This pull request
- Implements the feedback provided in https://github.com/tudat-team/tudatpy/pull/115 
- Provides a test to verify the exposure of C++ modules has been successful
- Modifies the top-level `__init__.y` kernel imports to attempt to fix the observed build issues for the MacOS and Windows builds. As the root of the issues seemed to be `.kernel.<modules>` imports[1], and the module exposure process does not at any point create such imports, it could be that the culprit is this file
[1]:
=> Porkchop plots and hybrid C++/Python kernel modules v2

.github/workflows/bump_dev_version_nightly.yml
This GitHub actions workflow runs daily at 3:00 AM and does the following if there has been new commit(s) on the develop branch of tudatpy in the last 24 hours:
1. Bump dev version: dev field of the version number in the files `version` and `.bumpversion.cfg` will be bumped by 1. This will result in a new commit.
2. Create a tag with the above version, and push the tag and the commit to the tudatpy develop branch
3. Bump dev version in tudat-feedstock: dev field of the version number in recipe/meta.yml and .bumpversion.cfg will be bumped by 1. This will result in a new commit.
4. Create a tag with the above version, and push the tag and the commit to the tudatpy-feedstock develop branch
**This workflow must be present in the master branch because scheduled workflows run only on the …
=> Nightly bump version workflow

.github/workflows/bump_dev_version_nightly.yml
Closes #181 
- Fix for the bug described in #181 : Install python dependency (nump2version) inside a python virtual environment instead of system-wide installation
- GITHUB_TOKEN is not needed for running the bumpversion command. This was mistakenly added previously, and now removed.
Changes are tested here:  https://github.com/niketagrawal/tudat/actions/workflows/bump_dev_version_tudat_and_tudat_feedstock.yml
=> Fix bump version workflow

cmake/YACMAPythonSetup.cmake
This fixes support for 3.12 where distutils is deprecated. The results of this change are seen In the feedstock via the patch of this change. [Azure](https://dev.azure.com/tudat-team/feedstock-builds/_build/results?buildId=1494&view=results)
=> fix(python3.12): Update Python setup script to use sysconfig

.github/workflows/bump_dev_version_nightly.yml
This PR targets the same command deprecation issue as seen in tudat bump version workflow: https://github.com/tudat-team/tudat/pull/267 in tudat
- set-output command will be deprecated soon as seen in the latest github actions log for the bump version workflow https://github.com/tudat-team/tudatpy/actions/runs/12003743168 
- See details in #195 
- Replace set-output with using Environment files because set-output will be deprecated soon. Rename step `should_run` to `should_bump_version` to avoid conflicting names for the step and the output variable. 
- Break down the command test -z $(git rev-list  --after="24 hours" $(git log -n 1 --pretty=format:"%H")) && echo "::set-output name=should_run::false" into multiple steps to improve readability.
- Remove obsolete output variable …
=> Replace deprecated set-output Command with Environment Files in Nightly Bump Workflow 

.gitmodules, docs/source/acceleration.rst, docs/source/environment_setup.rst, docs/source/ephemeris.rst, docs/source/radiation_pressure.rst, tudatpy/kernel/docstrings.h, tudatpy/kernel/expose_numerical_simulation/expose_environment_setup.cpp
A collection of minor API docs updates, WIP.
=> WIP: API docs updates

tudatpy/kernel/expose_data.cpp
Add numpy and eigen pybind header files to fix `read_vector_history_from_file` and `read_matrix_history_from_file` exposure.
Docs for the entire data module are missing from the API docs because the namespace in docstrings.h needs to be renamed from io to data (https://github.com/tudat-team/tudatpy/blob/develop/tudatpy/kernel/docstrings.h#L31374). Will be done either in #215 directly or after #215 has been merged.
=> Fix read function exposures

tudatpy/kernel/expose_numerical_simulation/expose_environment_setup/expose_ephemeris_setup.cpp
Since the fix will only apply to the dev build for now, the arguments will be passed explicitly in the example applications
=> fix TLE ephemeris default arguments to be Earth-centered

docs/source/conf.py
Update the announcement banner with links to the user guide and Github discussions forum (see screenshot below).
Other changes to conf.py file: Update the copyright year automatically based on build date, set docs language explicitly to English, update matplotlib intersphinx link to remove errors in sphinx build.
=> Update the announcement banner in API reference

docs/source/environment.rst, docs/source/time_conversion.rst, tudatpy/kernel/expose_astro/expose_element_conversion.cpp, tudatpy/kernel/expose_astro/expose_time_conversion.cpp, tudatpy/kernel/expose_interface/expose_spice.cpp, tudatpy/kernel/expose_math/expose_interpolators.cpp, tudatpy/kernel/expose_numerical_simulation/expose_environment_setup.cpp, tudatpy/kernel/expose_numerical_simulation/expose_propagation_setup/expose_acceleration_setup.cpp, tudatpy/kernel/expose_numerical_simulation/expose_propagation_setup/expose_integrator_setup.cpp, tudatpy/kernel/expose_numerical_simulation/expose_propagation_setup/expose_propagator_setup.cpp, tudatpy/kernel/expose_numerical_simulation_estimator.cpp, tudatpy/kernel/expose_numerical_simulation_variational.cpp
- Move enums and classes to beginning of `time_conversion` module so they can be resolved in function definitions
- Remove duplicate exposure of `keplerian_to_cartesian`
- Add note to `spice.get_body_gravitational_parameter` as distinction to default models
- Fix docstring and argument type of first derivative data in interpolators
=> Minor fixes

tudatpy/kernel/expose_numerical_simulation/expose_environment_setup/expose_vehicle_systems_setup.cpp
At the moment the default nullptr argument for the `panel_reflection_law` argument in the `body_panel_settings` function causes a segfault, unless explicitly overwritten. The default argument has been removed and should now throw an error (see https://github.com/tudat-team/tudat/pull/307 for corresponding tudat PR).
<details><summary>Segfault-throwing code for reference (should be resolved once PRs are merged)</summary>
<p>
```python
import matplotlib
import numpy as np
from matplotlib import pyplot as plt
from tudatpy import constants, numerical_simulation
from tudatpy.astro.time_conversion import DateTime
from tudatpy.interface import spice
from tudatpy.numerical_simulation import (environment, environment_setup,
propagation_setup)
spice.load_standard_kernels()
bodies_to_create = …
```
=> Remove default nullptr argument to avoid segfault

docs/source/spice.rst, tudatpy/kernel/expose_astro/expose_time_conversion.cpp, tudatpy/kernel/expose_numerical_simulation/expose_environment_setup.cpp, tudatpy/kernel/expose_numerical_simulation/expose_estimation_setup.cpp, tudatpy/kernel/expose_numerical_simulation/expose_propagation_setup.cpp, tudatpy/kernel/expose_numerical_simulation/expose_propagation_setup/expose_integrator_setup.cpp, tudatpy/kernel/expose_numerical_simulation/expose_propagation_setup/expose_propagator_setup.cpp, tudatpy/kernel/expose_numerical_simulation_estimator.cpp
Small fixes from the collection issue, including:
- Fix `year_and_days_in_year_to_calendar_date` exposure
- Update integrator settings #259
- Add references to step size control functions for `standard_cartesian_state_element_blocks` #260 
- Add code snippet with explanation how to create block indices for `step_size_control_blockwise_scalar_tolerance` and `step_size_control_blockwise_matrix_tolerance`
=> Small fixes to API docs

docs/source/constants.rst, docs/source/data.rst, docs/source/ephemeris.rst, docs/source/estimation.rst, docs/source/fundamentals.rst, docs/source/ground_station.rst, src/tudatpy/astro/element_conversion/expose_element_conversion.cpp, src/tudatpy/data/mission_data_downloader.py, src/tudatpy/math/interpolators/expose_interpolators.cpp, src/tudatpy/math/root_finders/expose_root_finders.cpp, src/tudatpy/numerical_simulation/environment/expose_environment.cpp, src/tudatpy/numerical_simulation/environment_setup/aerodynamic_coefficients/expose_aerodynamic_coefficients.cpp, src/tudatpy/numerical_simulation/environment_setup/gravity_field/expose_gravity_field.cpp, src/tudatpy/numerical_simulation/environment_setup/gravity_field_variation/expose_gravity_field_variation.cpp, src/tudatpy/numerical_simulation/estimation/expose_estimation_observation_collection.cpp, src/tudatpy/numerical_simulation/estimation_setup/parameter/expose_parameter.cpp, src/tudatpy/numerical_simulation/propagation_setup/acceleration/expose_acceleration.cpp, src/tudatpy/numerical_simulation/propagation_setup/dependent_variable/expose_dependent_variable.cpp, src/tudatpy/numerical_simulation/propagation_setup/integrator/expose_integrator.cpp, src/tudatpy/numerical_simulation/propagation_setup/propagator/expose_propagator.cpp
Second iteration of #270. All outstanding warnings when building the API docs have been fixed - no more red in the build process!
Main changes:
- Remove some duplicate and no-longer exposed functions
- Add blank lines around enum member docstrings. When pybind generates the docstring for enums, the enum member names are appended to a `"\n\n  "` string (see [pybind11.h#L2574](https://github.com/pybind/pybind11/blob/bc4a66dff0464d0c87291b00a3688999fea5bedc/include/pybind11/pybind11.h#L2574)). The two spaces before the member name make Sphinx interpret the member name as an indented quotation, which needs to be surrounded by blank lines. The user-defined docstrings are then [simply appended in pybind](https://github.com/pybind/pybind11/blob/bc4a66dff0464d0c87291b00a3688999fea5bedc/include/pyb …
=> Fix API doc warnings v2

.github/ISSUE_TEMPLATE/features---enhancements.md, .github/ISSUE_TEMPLATE/report-a-bug.md
Make it easier for users to follow new developing guidelines by setting up templates for pull requests.
The templates are based on the development guidelines suggested by @valeriof7 .
=> Create issue templates

cmake/PythonExtension.cmake, src/tudatpy/CMakeLists.txt
Modified `CMakeLists.txt` with a macro to copy all the Python scripts in tudatpy to the build directory during build, as it was done before the new setup. This makes it possible to import `tudatpy` from a script by manually adding the path to the build at the beginning of it.
NOTE: The `install.py` and `uninstall.py` scripts are still the recommended methods to work with the library. This patch is just meant to ensure backwards compatibility.
=> Allow for `sys.path.append` import [Backwards compatibility]

src/tudatpy/plotting/__init__.py
This PR fixes the imports of the plotting module such that stubs can be generated:
- Comment out deprecated ground track function imports
- Add explicit imports for plotting helper functions
=> Stubs for plotting module

src/tudatpy/astro/time_conversion/expose_time_conversion.cpp
This PR adds `__str__` and `__repr__` methods for the `DateTime` class.
At present, the string representation of DateTime objects is the default one generated by pybind, which only shows a memory address and is therefore not really helpful:
```
>>>print(DateTime(2000, 1, 1, 0, 0, 0))
<tudatpy.kernel.astro.time_conversion.DateTime object at 0x7f057ae283f0>
```
With the added dunder methods, the following output is produced from the `__str__` method:
```
>>>print(DateTime(2000, 1, 1, 0, 0, 0))
2000-01-01 00:00:00.000000000000000
```
and similarly from the `__repr__` method:
```
>>>DateTime(2000, 1, 1, 0, 0, 0)
DateTime(2000, 1, 1, 0, 0, 0.000000)
```
=> String and repr dunder methods for DateTime class

include/tudatpy/scalarTypes.h, src/tudatpy/numerical_simulation/environment_setup/radiation_pressure/expose_radiation_pressure.cpp, src/tudatpy/numerical_simulation/environment_setup/vehicle_systems/expose_vehicle_systems.cpp, src/tudatpy/numerical_simulation/propagation_setup/dependent_variable/expose_dependent_variable.cpp
Companion PR of tudat-team/tudat/pull/309 for the self-shadowing (SSH) feature.
Adds exposed functions to load macromodel geometry, merge parts and retrieve dependent variable with illuminated panel fractions. Documentation is also added.
=> Self-shadowing feature 

docs/source/aerodynamic_coefficients.rst, docs/source/environment.rst, docs/source/thrust.rst, src/tudatpy/astro/two_body_dynamics/expose_two_body_dynamics.cpp, src/tudatpy/numerical_simulation/environment_setup/atmosphere/expose_atmosphere.cpp, src/tudatpy/numerical_simulation/propagation_setup/propagator/expose_propagator.cpp
Fix errors in API docs builds;
- move `AerodynamicsReferenceFrameAngles`, `AerodynamicsReferenceFrames`, `AerodynamicCoefficientFrames`, `AerodynamicCoefficientsIndependentVariables`, `AtmosphericCompositionSpecies` to `aerodynamic_coefficients` module
- remove `get_propulsion_input_variables`
- remove erroneous class definitions in docstrings of `compute_escape_or_capture_delta_v`, `print_processed_state_indices`
- fix warnings in `nrlmsise00` atmosphere settings
=> Minor api doc fixes

docs/source/aerodynamic_coefficients.rst, docs/source/conf.py, docs/source/constants.rst, docs/source/dependent_variable.rst, docs/source/environment.rst, docs/source/frame_conversion.rst, docs/source/gravity_field.rst, docs/source/index.rst, docs/source/polyhedron_utilities.rst, docs/source/propagator.rst, docs/source/refs.bib, docs/source/shape_based_thrust.rst, docs/source/thrust.rst, docs/source/time_conversion.rst, docs/source/transfer_trajectory.rst, src/tudatpy/astro/frame_conversion/expose_frame_conversion.cpp, src/tudatpy/astro/polyhedron_utilities/expose_polyhedron_utilities.cpp, src/tudatpy/astro/two_body_dynamics/expose_two_body_dynamics.cpp, src/tudatpy/numerical_simulation/environment_setup/atmosphere/expose_atmosphere.cpp, src/tudatpy/numerical_simulation/environment_setup/gravity_field/expose_gravity_field.cpp, src/tudatpy/numerical_simulation/propagation_setup/dependent_variable/expose_dependent_variable.cpp, src/tudatpy/numerical_simulation/propagation_setup/propagator/expose_propagator.cpp, src/tudatpy/trajectory_design/transfer_trajectory/expose_transfer_trajectory.cpp
As discussed in the last developer meeting, this PR adds a global bibliography to the API reference. At the moment the bibliography is added on the index page, which can of course be modified!
Additionally, the citations are now created using the `sphinxcontrib.bibtex` package for more flexibility and easier bibliography maintenance.
> [!IMPORTANT]
> This PR builds on #309, which should be reviewed and merged first.
=> Add global bibliography to API docs

docs/source/time_conversion.rst, src/tudatpy/astro/time_conversion/expose_time_conversion.cpp
Expose `from_julian_day`, `from_modified_julian_day` and `to_days_since_reference_julian_day` methods implemented in https://github.com/tudat-team/tudat/pull/342, deprecate `julian_day_to_python_datetime`, `python_datetime_to_julian_day` and `python_datetime_to_days_since_epoch` functions.
Move all deprecated functions in `// deprecated` section.
=> JD and MJD static methods to construct DateTime

docs/source/ground_station.rst, src/tudatpy/numerical_simulation/environment_setup/ground_station/expose_ground_station.cpp
Add exposure to create a single DSN station, based on its station name.
Tudat companion PR: https://github.com/tudat-team/tudat/pull/349
=> Add exposure for function to create single DSN station

docs/source/conf.py, docs/source/dependent_variable.rst, docs/source/horizons.rst, src/tudatpy/data/mpc/mpc.py, src/tudatpy/numerical_simulation/environment_setup/ephemeris/horizons_wrapper.py, src/tudatpy/numerical_simulation/environment_setup/radiation_pressure/expose_radiation_pressure.cpp, src/tudatpy/numerical_simulation/propagation_setup/dependent_variable/expose_dependent_variable.cpp
Code examples for
- Setting up a radiation source model from an irradiance at a distance
- Convert a rotation matrix dependent variable from the row representation to a matrix
Exposures for
- Attributes of `SingleDependentVariableSaveSettings`, `SingleAccelerationDependentVariableSaveSettings` (this relies on https://github.com/tudat-team/tudat/pull/359)
Documentation for
- Dependent variable sizes (fixes #287)
- `get_dependent_variable_id`, `get_dependent_variable_size`, `get_dependent_variable_shape` functions
Added the `HorizonsBatch` class to the .rst files so they show up in the API docs.
=> Small API docs updates

src/tudatpy/numerical_simulation/estimation/__init__.py, src/tudatpy/numerical_simulation/estimation_setup/__init__.py, src/tudatpy/numerical_simulation/estimation_setup/observation/__init__.py, src/tudatpy/numerical_simulation/estimation_setup/parameter/__init__.py
When building the merged tudatpy repository, the stub generation fails due to invalid characters in the deprecation warnings:
```
[100%] Linking CXX shared module kernel.so
[100%] Built target kernel
Generating stubs for tudatpy.kernel...
pybind11_stubgen - [  ERROR] In tudatpy.kernel.astro.element_conversion.convert_position_elements : Invalid expression 'tudat::basic_astrodynamics::BodyShapeModel'
< omitting invalid expression errors>
pybind11_stubgen - [  ERROR] In tudatpy.kernel.trajectory_design.transfer_trajectory.set_low_thrust_acceleration : Invalid expression 'tudat::simulation_setup::SystemOfBodies'
pybind11_stubgen - [WARNING] Enum-like str representations were found with no matching mapping to the enum class location.
Use `--enum-class-locations` to specify full path to the …
```
=> Fix deprecation warnings strings to avoid invalid characters

src/tudatpy/numerical_simulation/environment_setup/vehicle_systems/expose_vehicle_systems.cpp
Fixed exposure of function `body_panel_settings`, as it was missing the overload cast.
Soon I will also create the `develop_10` PR.
=> Fixed exposure of body panel settings

docs/tudatpy/source/estimation/estimation_analysis.rst, src/tudatpy/dynamics/parameters_setup/expose_parameters_setup.cpp, src/tudatpy/estimation/estimation_analysis/expose_estimation_analysis.cpp
This PR changes:
- The input to the `propagate_covariance_rsw_split_output` and `propagate_formal_errors_rsw_split_output` functions is made consistent with the other Cov/FE propagation functions, to take the initial covariance as an input instead of a `CovarianceAnalysisOutput` object. This allows to also propagate a consider covariance matrix, which before would throw an error due to a size mismatch of the STM/Sensitivity Matrix interface (which includes the consider parameters) and the covariance matrix requested from the `CovarianceAnalysisOutput` object (which did not include the consider parameter portion)
- The RSW Cov/FE propagation functions are documented and added to the API docs
- The parameter identifier attribute of the `EstimatableParameterSettings` class is exposed
=> Make COV/FE RSW propagation input consistent, minor exposure/docs updates

src/tudatpy/astro/gravitation/expose_gravitation.cpp, src/tudatpy/dynamics/simulator/expose_simulator.cpp, src/tudatpy/estimation/estimation_analysis/expose_estimation_analysis.cpp
- Expose `state_transition_interface` attribute in `VariationalSimulator` base class
- Add docs for remaining `CovarianceAnalysisOutput` attributes, expose `unnormalized_design_matrix_consider_parameters`
=> Expose stm interface attribute
